apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bonus-app
  namespace: argocd
spec:
  project: default
  source:
    # Points to the local VM IP we defined in the Vagrantfile
    repoURL: 'http://192.168.56.120/root/iot-bonus.git'
    targetRevision: HEAD
    path: ./
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dev
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true