apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: part3-khbouych-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/khalidbouychou/iot-p3.git'
    targetRevision: HEAD
    path: ./
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dev
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true