Vagrant.configure(2) do |config|
  config.vm.box = "debian/bookworm64"
  config.vm.box_version = "12.20240610.1"
  
  config.vm.define "khbouyS" do |server|
    server.vm.hostname = "khbouyS"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.provider "virtualbox" do |v|
      v.name = "khbouyS"
      v.memory = 1024
      v.cpus = 1
    end
    
    server.vm.provision "shell", inline: <<-SHELL
      apt-get update && apt-get upgrade -y
      apt-get install -y curl wget
    SHELL
    
    server.vm.provision "shell", path: "scripts/install_k3s.sh"
    server.vm.provision "shell", path: "scripts/deploy_apps.sh"
  end
end
