# -*- mode: ruby -*-
Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/focal64"
  config.vm.network "public_network" , ip:"192.168.56.110"
  config.vm.provision "shell", inline: <<-SHELL
   curl -sfL https://get.k3s.io | sh 
   /sudo cp /etc/rancher/k3s/k3s.yaml /vagrant/kubconfig
   SHELL
end
