Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"

  # SERVER
  config.vm.define "khbouychS" do |server|
    server.vm.hostname = "khbouychS"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
    end

    server.vm.provision "shell", path: "scripts/install_k3s_server.sh"
  end

  # WORKER
  config.vm.define "khbouychSW" do |worker|
    worker.vm.hostname = "khbouychSW"
    worker.vm.network "private_network", ip: "192.168.56.111"
    worker.vm.provider "virtualbox" do |vb|
      vb.memory = 512
      vb.cpus = 1
    end

    worker.vm.provision "shell", path: "scripts/install_k3s_agent.sh"
  end
end