Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-22.04"

  config.vm.define "khbouychS" do |s|
    s.vm.hostname = "khbouychS"
    s.vm.network "private_network", ip: "192.168.56.110"
    s.vm.provider "virtualbox" do |vb|
      vb.name = "khbouychS"
      vb.memory = 1024
      vb.cpus = 1
    end
    s.vm.provision "shell", path: "scripts/server.sh"
  end

  config.vm.define "khbouychSW" do |w|
    w.vm.hostname = "khbouychSW"
    w.vm.network "private_network", ip: "192.168.56.111"
    w.vm.provider "virtualbox" do |vb|
      vb.name = "khbouychSW"
      vb.memory = 1024
      vb.cpus = 1
    end
    w.vm.provision "shell", path: "scripts/worker.sh"
  end
end