Vagrant.configure(2) do |config|
  config.vm.box = "debian/bookworm64"
  config.vm.box_version = "12.20240610.1"
  
  config.vm.define "khbouyGitlab" do |gitlab|
    gitlab.vm.hostname = "khbouyGitlab"
    gitlab.vm.network "private_network", ip: "192.168.56.113"
    gitlab.vm.provider "virtualbox" do |v|
      v.name = "khbouyGitlab"
      v.memory = 4096
      v.cpus = 4
    end
    
    gitlab.vm.provision "shell", inline: <<-SHELL
      apt-get update && apt-get upgrade -y
      apt-get install -y curl wget git vim htop net-tools
    SHELL
    
    gitlab.vm.provision "shell", path: "scripts/setup_docker.sh"
    gitlab.vm.provision "shell", path: "scripts/setup_helm.sh"
    gitlab.vm.provision "shell", path: "scripts/setup_k3d.sh"
    gitlab.vm.provision "shell", path: "scripts/setup_gitlab.sh"
    gitlab.vm.provision "shell", path: "scripts/setup_argocd_gitlab.sh"
  end
end
