Vagrant.configure(2) do |config|
  config.vm.box = "debian/bookworm64"
  config.vm.box_version = "12.20240610.1"
  
  config.vm.define "khbouyK3d" do |k3d|
    k3d.vm.hostname = "khbouyK3d"
    k3d.vm.network "private_network", ip: "192.168.56.112"
    k3d.vm.provider "virtualbox" do |v|
      v.name = "khbouyK3d"
      v.memory = 2048
      v.cpus = 2
    end
    
    k3d.vm.provision "shell", inline: <<-SHELL
      apt-get update && apt-get upgrade -y
      apt-get install -y curl wget git
    SHELL
    
    k3d.vm.provision "shell", path: "scripts/setup_k3d.sh"
    k3d.vm.provision "shell", path: "scripts/setup_argocd.sh"
  end
end
